"""
Deterministic clinical rule engine for vital signs anomaly detection and risk scoring.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional

from src.config import VitalThresholds
from src.preprocessing import VitalSummary


class SeverityLevel(str, Enum):
    NORMAL = "NORMAL"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


@dataclass
class ClinicalDiagnosis:
    """Diagnostic outcome generated by deterministic rule-based analysis."""
    conditions: List[str] = field(default_factory=list)
    severity: SeverityLevel = SeverityLevel.NORMAL
    is_abnormal: bool = False
    explanation: str = "All measured vital signs are within normal clinical thresholds."


class RulesEngine:
    """
    Evaluates vital parameters against clinical thresholds to detect
    acute physiological abnormalities and multi-system risk patterns.
    """

    def __init__(self, thresholds: Optional[VitalThresholds] = None):
        self.thresholds = thresholds or VitalThresholds()

    def evaluate(
        self,
        temperature: Optional[float] = None,
        heart_rate: Optional[float] = None,
        spo2: Optional[float] = None,
    ) -> ClinicalDiagnosis:
        """
        Evaluate individual or average vital signs against clinical rules.
        """
        conditions: List[str] = []
        severity = SeverityLevel.NORMAL

        t = self.thresholds

        # 1. Temperature evaluation
        if temperature is not None:
            if temperature > t.fever_temp_c:
                conditions.append(f"Fever detected (Temp: {temperature:.1f} °C > {t.fever_temp_c} °C)")
                severity = max(severity, SeverityLevel.WARNING, key=lambda s: s.value)
            elif temperature < t.hypothermia_temp_c:
                conditions.append(f"Hypothermia warning (Temp: {temperature:.1f} °C < {t.hypothermia_temp_c} °C)")
                severity = SeverityLevel.CRITICAL

        # 2. Oxygen Saturation evaluation
        if spo2 is not None:
            if spo2 < t.severe_hypoxemia_spo2:
                conditions.append(f"Severe hypoxemia (SpO₂: {spo2:.1f}% < {t.severe_hypoxemia_spo2}%) - Urgent evaluation required")
                severity = SeverityLevel.CRITICAL
            elif spo2 < t.hypoxemia_spo2:
                conditions.append(f"Low SpO₂ (SpO₂: {spo2:.1f}% < {t.hypoxemia_spo2}%) - Hypoxemia risk")
                severity = max(severity, SeverityLevel.WARNING, key=lambda s: s.value)

        # 3. Heart Rate evaluation
        if heart_rate is not None:
            if heart_rate > t.tachycardia_hr:
                conditions.append(f"Tachycardia (Pulse: {heart_rate:.0f} BPM > {t.tachycardia_hr} BPM)")
                severity = max(severity, SeverityLevel.WARNING, key=lambda s: s.value)
            elif heart_rate < t.bradycardia_hr:
                conditions.append(f"Bradycardia (Pulse: {heart_rate:.0f} BPM < {t.bradycardia_hr} BPM)")
                severity = max(severity, SeverityLevel.WARNING, key=lambda s: s.value)

        # 4. Multi-vital compound interaction rules
        if temperature is not None and spo2 is not None:
            if temperature > t.fever_temp_c and spo2 < t.hypoxemia_spo2:
                conditions.append("Compound Risk: Fever + Low SpO₂ → Possible respiratory infection / pneumonia")
                severity = max(severity, SeverityLevel.WARNING, key=lambda s: s.value)

        if heart_rate is not None and spo2 is not None:
            if heart_rate > t.tachycardia_hr and spo2 < t.hypoxemia_spo2:
                conditions.append("Compound Risk: Tachycardia + Low SpO₂ → Hypoxemia or acute cardiopulmonary distress")
                severity = SeverityLevel.CRITICAL

        if temperature is not None and heart_rate is not None:
            if temperature > t.high_fever_temp_c and heart_rate > t.tachycardia_hr:
                conditions.append("Critical Compound Risk: High fever + Tachycardia → Possible sepsis or systemic infection")
                severity = SeverityLevel.CRITICAL

        is_abnormal = len(conditions) > 0

        explanation = (
            "\n".join([f"• {c}" for c in conditions])
            if is_abnormal
            else "All measured vital signs are within normal clinical thresholds."
        )

        return ClinicalDiagnosis(
            conditions=conditions,
            severity=severity,
            is_abnormal=is_abnormal,
            explanation=explanation,
        )

    def evaluate_summary(self, summary: VitalSummary) -> ClinicalDiagnosis:
        """Evaluate aggregated vital summary."""
        return self.evaluate(
            temperature=summary.avg_temp,
            heart_rate=summary.avg_hr,
            spo2=summary.avg_spo2,
        )
